import{a as c,S as f,i as u}from"./assets/vendor-B4VkUtbg.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m="16575326-2aaf0836bf0e7c9f61deb233c";function d(r){return c("https://pixabay.com/api/",{params:{key:m,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}})}const p=new f(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),l={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),loader:document.querySelector(".loader")};function y(){l.gallery.innerHTML=""}function g(r){console.log("create : ",r),l.gallery.innerHTML=r.map(({largeImageURL:o,webformatURL:i,tags:s,likes:e,views:t,comments:a,downloads:n})=>`<li class="gallery-item">
            <a class="gallery-item-link" href="${o}"><img src="${i}" alt="${s}"></a>
            <ul class="gallery-img-info">
              <li class="gallery-info-item">Likes <span>${e}</span></li>
              <li class="gallery-info-item">Views <span>${t}</span></li>
              <li class="gallery-info-item">Comments <span>${a}</span></li>
              <li class="gallery-info-item">Downloads <span>${n}</span></li>
            </ul>
      </li>`).join(""),p.refresh()}function h(){l.loader.classList.add("show")}function L(){l.loader.classList.remove("show")}l.form.addEventListener("submit",b);function b(r){r.preventDefault();const o=r.currentTarget.elements["search-text"].value.trim();y(),h(),d(o).then(({data:{hits:i}})=>{i.length>0?g(i):w(`Sorry, there are no images matching your ${o}. Please try again!`)}).catch(i=>console.log(i)).finally(()=>L())}function w(r){u.error({position:"topRight",message:r})}
//# sourceMappingURL=index.js.map
